apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxies
  namespace: nm-proxies
  labels:
    app: proxies
spec:
  replicas: 5
  selector:
    matchLabels:
      app: proxies
  template:
    metadata:
      labels:
        app: proxies
    spec:
      containers:
        - name: proxies
          image: docker.io/kworkdevsecops/proxies:latest
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: docker-secrets
