---
- name: Setting up our cloud
  ansible.builtin.import_playbook: ./system/import.yaml
  tags: [system]

- name: Installing required packages
  ansible.builtin.import_playbook: ./packages/import.yaml
  tags: [packages]

- name: Installing kubernetes-full
  ansible.builtin.import_playbook: ./kubernetes/import.yaml
  tags: [kubernetes]

- name: System update and restart
  ansible.builtin.import_playbook: ./end/update.yaml
  tags: [end]
