global:
  domain: argo.collaboo.co
  imagePullSecrets:
    - name: docker-secrets

server:
  ingress:
    enabled: false

  service:
    type: ClusterIP
    ports:
      http:
        port: 80
        targetPort: 8080

configs:
  params:
    server.insecure: "true"
    server.resource.customresourcedefinitions: "true"
    server.namespaces: "nm-argo"
    server.basehref: "/"
    server.rootpath: ""
