---
- name: Installing cert-manager // infra/ansible/playbook/kubernetes/helm/cert-manager/install.yaml
  hosts: dev
  become: true

  tasks:
    - name: Add cert-manager chart repository to Helm
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/helm/cert-manager/values.yaml
        dest: /root/cert.yaml
        remote_src: false

    - name: Install cert-manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: nm-cert-manager
        values_files:
          - /root/cert.yaml
        wait: true

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        path: /root/cert.yaml
        state: absent
