---
- name: Creating PVCs // infra/ansible/playbook/kubernetes/default/storage/pvc.yaml
  hosts: dev
  become: true
  tasks:
    - name: PersistentVolumeClaim for promtail
      kubernetes.core.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: nm-monitoring
        name: loki-pvc
        state: present
        resource_definition:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: local-path

    - name: PersistentVolumeClaim for prometheus
      kubernetes.core.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: nm-monitoring
        name: prometheus-pvc
        state: present
        resource_definition:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: local-path

    - name: PersistentVolumeClaim for grafana
      kubernetes.core.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: nm-monitoring
        name: grafana-pvc
        state: present
        resource_definition:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: local-path

    # TODO

    # - name: PersistentVolumeClaim for proxies-prod
    #   kubernetes.core.k8s:
    #     api_version: v1
    #     kind: PersistentVolumeClaim
    #     namespace: nm-proxies
    #     name: proxies-pvc
    #     state: present
    #     resource_definition:
    #       spec:
    #         accessModes:
    #           - ReadWriteOnce
    #         resources:
    #           requests:
    #             storage: 5Gi
    #         storageClassName: local-path

    # - name: PersistentVolumeClaim for proxies-test
    #   kubernetes.core.k8s:
    #     api_version: v1
    #     kind: PersistentVolumeClaim
    #     namespace: nm-develop
    #     name: proxies-pvc
    #     state: present
    #     resource_definition:
    #       spec:
    #         accessModes:
    #           - ReadWriteOnce
    #         resources:
    #           requests:
    #             storage: 5Gi
    #         storageClassName: local-path
