---
- name: Creating storageclass // infra/ansible/playbook/kubernetes/default/storage/storage.yaml
  hosts: dev
  become: true
  tasks:
    - name: Download local-path-provisioner manifest
      ansible.builtin.copy:
        src: ./local-patch.yaml
        dest: /tmp/local-path-provisioner.yaml
        mode: "0644"
        remote_src: false

    - name: Apply local-path-provisioner manifest
      kubernetes.core.k8s:
        state: present
        src: /tmp/local-path-provisioner.yaml

    - name: Patch storageclass to be default
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: local-path
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
