apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-craftwork
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "craftwork"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: "craftwork.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-envato
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "envato"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: "elements.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-flaticon
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "flaticon"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: "flaticon.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
              
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-freepik
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "freepik"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: "freepik.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-iconly
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "iconly"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: "iconly.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-mobbin
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/request-modifier: "X-Target-Site: mobbin"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: "mobbin.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-refero
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "refero"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: "refero.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-uxmovement
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "uxmovement"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: "uxmove.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80