apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-craftwork
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "craftwork"
spec:
  ingressClassName: traefik
  rules:
    - host: "craftwork.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-envato
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "envato"
spec:
  ingressClassName: traefik
  rules:
    - host: "elements.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-flaticon
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "flaticon"
spec:
  ingressClassName: traefik
  rules:
    - host: "flaticon.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-freepik
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "freepik"
spec:
  ingressClassName: traefik
  rules:
    - host: "freepik.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-iconly
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "iconly"
spec:
  ingressClassName: traefik
  rules:
    - host: "iconly.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-mobbin
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "mobbin"
spec:
  ingressClassName: traefik
  rules:
    - host: "mobbin.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-refero
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "refero"
spec:
  ingressClassName: traefik
  rules:
    - host: "refero.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-uxmovement
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "uxmovement"
spec:
  ingressClassName: traefik
  rules:
    - host: "uxmove.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-dev-craftwork
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "dev-craftwork"
spec:
  ingressClassName: traefik
  rules:
    - host: "dev-craftwork.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-dev-envato
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "dev-elements"
spec:
  ingressClassName: traefik
  rules:
    - host: "dev-elements.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-dev-flaticon
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "dev-flaticon"
spec:
  ingressClassName: traefik
  rules:
    - host: "dev-flaticon.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-dev-freepik
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "dev-freepik"
spec:
  ingressClassName: traefik
  rules:
    - host: "dev-freepik.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-dev-iconly
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "dev-iconly"
spec:
  ingressClassName: traefik
  rules:
    - host: "dev-iconly.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-dev-mobbin
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "dev-mobbin"
spec:
  ingressClassName: traefik
  rules:
    - host: "dev-mobbin.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-dev-refero
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "dev-refero"
spec:
  ingressClassName: traefik
  rules:
    - host: "dev-refero.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-backend-dev-uxmove
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/custom-request-headers.X-Target-Site: "dev-uxmovement"
spec:
  ingressClassName: traefik
  rules:
    - host: "dev-uxmove.collaboo.co"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-backend
                port:
                  number: 80
