---
- name: Create docker-registry secrets // infra/ansible/playbook/kubernetes/default/secrets/docker.yaml
  hosts: dev
  become: true
  vars_files:
    - ../../../secrets/secrets.yaml
  vars:
    namespaces:
      - nm-proxies
      - nm-argo
      - nm-monitoring
      - nm-traefik
      - local-path-storage

  tasks:
    - name: Create docker-registry secret in each namespace
      ansible.builtin.shell: |
        kubectl create secret docker-registry docker-secrets \
          --docker-username={{ docker_registry_username }} \
          --docker-password={{ docker_registry_password }} \
          -n {{ item }} --dry-run=client -o yaml | kubectl apply -f -
      loop: "{{ namespaces }}"
      loop_control:
        label: "{{ item }}"
