global:
  image:
    registry: docker.io

imagePullSecrets:
  - name: docker-secrets

loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  querier:
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

deployment_mode: SimpleScalable

ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistence:
    enabled: true
    storageClass: loki-pvc
    size: 10Gi

querier:
  replicas: 1
  maxUnavailable: 0

queryFrontend:
  replicas: 1
  maxUnavailable: 0

queryScheduler:
  replicas: 1

distributor:
  replicas: 1
  maxUnavailable: 0

compactor:
  replicas: 1

indexGateway:
  replicas: 1
  maxUnavailable: 0

bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

gateway:
  service:
    type: ClusterIP

minio:
  enabled: true

resultsCache:
  enabled: true
  image:
    registry: docker.io
    repository: memcached
    tag: "1.6.39-alpine"
    pullPolicy: IfNotPresent
  exporter:
    image:
      registry: docker.io
      repository: prom/memcached-exporter
      tag: "v0.15.3"
      pullPolicy: IfNotPresent

chunksCache:
  enabled: true
  image:
    registry: docker.io
    repository: memcached
    tag: "1.6.39-alpine"
    pullPolicy: IfNotPresent
  exporter:
    image:
      registry: docker.io
      repository: prom/memcached-exporter
      tag: "v0.15.3"
      pullPolicy: IfNotPresent

singleBinary:
  enabled: false
