name: CI/CD - Build Docker & Deploy via Helm

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/kworkdevsecops/proxies:latest

  deploy-helm:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        id: install

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure Kubernetes
        run: |
          mkdir ~/.kube/ && echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          export KUBECONFIG=~/.kube/config
          cd infra/helm/proxy-backend
          helm upgrade proxy-backend . --install --namespace default --values values.yaml --wait --timeout 5m
          kubectl rollout restart deployment/proxy-backend -n default && kubectl rollout status deployment/proxy-backend -n default --timeout=5m
