name: CI Pipeline

on:
  push:
    branches:
      - test

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker.hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.TEST_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TEST_DOCKERHUB_TOKEN }}

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: docker.io/${{ secrets.TEST_DOCKERHUB_USERNAME }}/test_proxies:latest
